### PR TITLE
!cat replacement

### PR DESCRIPTION
**Pull request by Tomoli75**
@RedstoneDaedalus
# New
## Fixes/Changes:
1. !cat now pulls from https://verifybot.tomoli.cf/cat.php, which pulls from 3 APIs, moderated by contributors with a key
2. Added me to credits (feel free to remove, change or whatever)

## Detailed Descriptions:
1. The cat command now pulls from thecatapi.com, random.cat and also the community can upload their own cat pictures, which are moderated also.

## Reasoning For Addition:
1. Truly random cats
2. Improve the command so the cats aren't hardcoded

## Other Notes:
1. The cooldown can be lowered due to the server's ping and internet speed

# Old
## Fixes/Changes:
1. !cat now pulls from https://verifybot.tomoli.cf/cat.php, which pulls from 3 different APIs
2. Added me to credits (feel free to remove, change or whatever)

## Detailed Descriptions:
1. The cat command now pulls from thecatapi.com, random.cat and also a file-based system, which can be added to by messaging me, or using FTP (details on request).

## Reasoning For Addition:
1. Truly random cats
2. Improve the command so the cats aren't hardcoded

## Other Notes:
1. The cooldown can be lowered due to the server's ping and internet speed

### CODE REVIEW

**Comment by ArtificialLegacy** [comment]
i thought we didn't do this because there were inappropriate images in the cat APIs ^^

**Comment by DerpyTheCoder** [comment]
Exactly. I will look into updating this command with new cats soon™

**Comment by Tomoli75** [comment]
I could remove the cat APIs and make a quick web page where you can upload your own cat pictures, and they'd be moderated by contributors to this repo?

**Comment by Tomoli75** [comment]
The prototype is done, and it's all verified by the contributors. I'll show you how to use it if I can get into the verifybot dev discord, so I don't have to share a secret key on github.

**Comment by Tomoli75** [comment]
I've done a bit more of updating and extended it to !dog. Doesn't need special testing as framework from !dog command was used, and that was previously functional. Just mention me in VerifyBot discord and I'll show you how it works.

**Comment by Tomoli75** [comment]
@RedstoneDaedalus Can you come into the verifybot test chat, I can explain why this PR should get through

**Pull request closed without merging**
