### PR TITLE
!math

### PR DESCRIPTION
**Pull request by LittleWhole**
@RedstoneDaedalus

## Fixes/Changes:
1. Creating a new command called !math, an overhaul for !calc.

## Detailed Descriptions:
1. !math can evaluate pretty much mathematical expression it gets thrown at it.

## Reasoning For Addition:
1. !calc was too limited.

### CODE REVIEW

**Comment by LittleWhole** [comment]
To show you that it works (really well), here are some images.
image
image
image
image
image

**Comment by SiebeDW** [comment]
Im right this needs 'npm i' to make this work.

**Comment by LittleWhole** [comment]
> 
> 
> Im right this needs 'npm i' to make this work.

It does, that's why I edited `package.json`

**Comment by Tomoli75** [comment]
Maybe remove !calc to stop people being confused, as !math is clearly better.

**Comment by LittleWhole** [comment]
> 
> 
> Maybe remove !calc to stop people being confused, as !math is clearly better.

Good idea. I merged the functions of calc that math can't do. I'll delete calc.

**Comment by Tomoli75** [comment]
🎉

**Pull request merged**
